### ISSUE TITLE
安装插件后开机提示[ERROR] nonebot | Failed to import "nonebot_plugin_l4d2_server"

### ISSUE THREAD

**Issue by wulingyijiu** [Agnes4m/nonebot_plugin_l4d2_server#43]
控制台输出
01-13 11:27:44 [ERROR] nonebot | Failed to import "nonebot_plugin_l4d2_server"
Traceback (most recent call last):
  File "<string>", line 14, in <module>
  File "C:\Users\Administrator\l4d2\.venv\lib\site-packages\nonebot\plugin\load.py", line 130, in load_from_toml
    return load_all_plugins(plugins, plugin_dirs)
  File "C:\Users\Administrator\l4d2\.venv\lib\site-packages\nonebot\plugin\load.py", line 64, in load_all_plugins
    return manager.load_all_plugins()
  File "C:\Users\Administrator\l4d2\.venv\lib\site-packages\nonebot\plugin\manager.py", line 176, in load_all_plugins
    return set(
  File "C:\Users\Administrator\l4d2\.venv\lib\site-packages\nonebot\plugin\manager.py", line 177, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
> File "C:\Users\Administrator\l4d2\.venv\lib\site-packages\nonebot\plugin\manager.py", line 142, in load_plugin
    module = importlib.import_module(name)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "C:\Users\Administrator\l4d2\.venv\lib\site-packages\nonebot\plugin\manager.py", line 242, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\Administrator\l4d2\.venv\lib\site-packages\nonebot_plugin_l4d2_server\__init__.py", line 33, in <module>
    from .l4d2_data import sq_L4D2
  File "C:\Users\Administrator\l4d2\.venv\lib\site-packages\nonebot_plugin_l4d2_server\l4d2_data\__init__.py", line 5, in <module>
    from ..l4d2_utils.config import (
  File "C:\Users\Administrator\l4d2\.venv\lib\site-packages\nonebot_plugin_l4d2_server\l4d2_utils\config.py", line 142, in <module>
    config_manager = L4d2ConfigManager()
  File "C:\Users\Administrator\l4d2\.venv\lib\site-packages\nonebot_plugin_l4d2_server\l4d2_utils\config.py", line 110, in __init__
    yaml.load(
  File "C:\Users\Administrator\l4d2\.venv\lib\site-packages\ruamel\yaml\main.py", line 1085, in load
    error_deprecation('load', 'load', arg=_error_dep_arg, comment=_error_dep_comment)
  File "C:\Users\Administrator\l4d2\.venv\lib\site-packages\ruamel\yaml\main.py", line 1039, in error_deprecation
    raise AttributeError(s, name=None)
AttributeError:
"load()" has been removed, use

  yaml = YAML(typ='rt')
  yaml.load(...)

and register any classes that you use, or check the tag attribute on the loaded data,
instead of file "C:\Users\Administrator\l4d2\.venv\lib\site-packages\nonebot_plugin_l4d2_server\l4d2_utils\config.py", line 110

                yaml.load(

Package                 Version
----------------------- ---------------
anyio                   3.7.1
APScheduler             3.10.4
arrow                   1.3.0
bcrypt                  4.1.2
binaryornot             0.4.4
cashews                 6.4.0
certifi                 2023.11.17
chardet                 5.2.0
charset-normalizer      3.3.2
click                   8.1.7
colorama                0.4.6
cookiecutter            2.5.0
dateparser              1.2.0
distlib                 0.3.8
exceptiongroup          1.2.0
fastapi                 0.95.2
filelock                3.13.1
h11                     0.14.0
httpcore                0.17.3
httptools               0.6.1
httpx                   0.24.1
idna                    3.6
Jinja2                  3.1.3
loguru                  0.7.2
markdown-it-py          3.0.0
MarkupSafe              2.1.3
mdurl                   0.1.2
nb-cli                  1.2.8
nb-cli-plugin-bootstrap 0.1.6
nb-cli-plugin-webui     0.4.0
noneprompt              0.1.9
passlib                 1.7.4
pathlib                 1.0.1
pip                     23.3.2
platformdirs            4.1.0
prompt-toolkit          3.0.43
psutil                  5.9.7
pydantic                1.10.13
pyfiglet                0.8.post1
Pygments                2.17.2
PyJWT                   2.8.0
python-dateutil         2.8.2
python-dotenv           1.0.0
python-slugify          8.0.1
pytz                    2023.3.post1
pywin32                 306
PyYAML                  5.3.1
regex                   2023.12.25
requests                2.31.0
rich                    13.7.0
setuptools              65.5.0
six                     1.16.0
sniffio                 1.3.0
socksio                 1.0.0
starlette               0.27.0
text-unidecode          1.3
tomlkit                 0.12.3
types-python-dateutil   2.8.19.20240106
typing_extensions       4.9.0
tzdata                  2023.4
tzlocal                 5.2
urllib3                 2.1.0
uvicorn                 0.22.0
virtualenv              20.25.0
watchfiles              0.21.0
wcwidth                 0.2.13
websockets              12.0
win32-setctime          1.1.0
WMI                     1.5.1

**Comment by Agnes4m** [comment]
pip install "ruamel.yaml"==0.17.21

**Comment by Agnes4m** [comment]
现在还有问题吗，抱歉之前因为其他事情忘了这个插件了，现在来看看还有啥要改的
